name: Sauce Labs CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: googlechrome-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress
